name: Release for HACS

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate and release for HACS
        uses: hacs/action@22.5.0
        with:
          category: plugin
